data <- df_2021
key_data_col_name <- GEO_FROM
tc_data <- updated_df_corr_2021
key_tc_data_col_name <- GEO_FROM
var_names <- var_name
filter_vars <- filter_names
tc_type <- "backward"
valu_type <- "p"
geo_to_name <- GEO_TO
uncertainty_colname <- "attendance_level_uncertainty_correspondence"
